### PR TITLE
Gravwell Kit: Add Dashboard for Data Ingestion

### PR DESCRIPTION
**Pull request by Lawrence-Wellman-Gravwell**
Add Dashboard for Data Ingestion, Add tags to resources, Change Queries to multiline, rename dashboards and searches.

### CODE REVIEW

**Comment by ashnwade** [comment]
Looks like we still need to bump the kit version

**Comment by keith-smiley-gravwell** [comment]
I believe the CONVERT_BYTES_GB macro is missing

**Comment by keith-smiley-gravwell** [comment]
Need to add the TARGET_INGEST macro as well
Also for some reason I get 2 each of the following:
  - "Update ingester table" scheduled searches
  - "Tag Aggregates" flows
  - "Ingester state tracker
...is that just me?

**Comment by keith-smiley-gravwell** [comment]
FYI the duplicate items were on my end

**Review by mike-wade-gravwell — APPROVED** [review]
LGTM!

**Pull request merged**
